# Generated by Django 3.0.7 on 2023-05-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0003_auto_20230510_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'TeamHead'), (3, 'TeamMem')], default=1, max_length=10),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
