# Generated by Django 3.0.7 on 2023-05-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0005_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='head_id',
        ),
    ]
