# Generated by Django 3.2.9 on 2023-05-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0008_auto_20230514_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_complete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_complete',
        ),
    ]
