# Generated by Django 3.2.9 on 2023-05-14 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0009_auto_20230514_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_create',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_due_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_intro',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_title',
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
