# Generated by Django 3.2.9 on 2023-05-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0010_auto_20230514_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamhead',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teammem',
            name='address',
        ),
    ]
