# Generated by Django 3.2.9 on 2023-05-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0015_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_complete',
        ),
    ]
