# Generated by Django 3.2.9 on 2023-05-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0016_remove_task_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(blank=True, choices=[('1', 'New'), ('2', 'Active'), ('3', 'Completed')], max_length=200, null=True),
        ),
    ]
