# Generated by Django 3.2.9 on 2023-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0023_auto_20230520_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_member',
            field=models.ManyToManyField(to='TaskManagement_app.TeamMem'),
        ),
    ]
