# Generated by Django 3.2.9 on 2023-05-21 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0024_task_task_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_member',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TaskManagement_app.teammem'),
            preserve_default=False,
        ),
    ]
