# Generated by Django 3.2.9 on 2023-05-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0026_auto_20230522_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_report',
            field=models.FileField(blank=True, null=True, upload_to='progress_reports/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', to='TaskManagement_app.TeamMem'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(blank=True, choices=[('1', 'New'), ('2', 'In Progress'), ('3', 'Completed')], max_length=200, null=True),
        ),
    ]
