# Generated by Django 3.2.9 on 2023-06-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0027_auto_20230531_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='progress_report',
        ),
    ]
