# Generated by Django 3.2.9 on 2023-06-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0028_remove_task_progress_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_report',
            field=models.TextField(blank=True),
        ),
    ]
