# Generated by Django 3.2.9 on 2023-06-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0029_task_progress_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(related_name='projects', to='TaskManagement_app.Task'),
        ),
    ]
