# Generated by Django 3.2.9 on 2023-06-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0032_auto_20230609_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginlogout',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
