# Generated by Django 3.2.9 on 2023-06-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0033_userloginlogout_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_logged_in',
        ),
        migrations.DeleteModel(
            name='UserLoginLogout',
        ),
    ]
