# Generated by Django 3.2.9 on 2023-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0034_auto_20230609_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamhead',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamhead',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teamhead',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teamhead',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='teammem',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammem',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teammem',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teammem',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
