# Generated by Django 3.2.9 on 2023-06-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0036_auto_20230612_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamhead',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='teamhead',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teammem',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='teammem',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='profile_pics/'),
        ),
    ]
