# Generated by Django 3.2.9 on 2023-06-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement_app', '0037_auto_20230613_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamhead',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
